/**
 * EC-01 — Knowledge Graph — nós oficiais do domínio.
 */

import type { GraphEntityId, GraphNode } from "@/app/lib/domain/graph/types";

export const DOMAIN_GRAPH_NODES: Record<GraphEntityId, GraphNode> = {
  User: {
    id: "User",
    label: "Usuário",
    dependsOn: [],
    affects: ["Payment", "Appointment", "Service", "Coupon", "Plan", "Dashboard", "Statistics"],
    usedBy: ["minha-conta", "auth", "workflow"],
    producesEvents: ["UserRegistered"],
    consumesEvents: ["PaymentConfirmed", "PlanActivated"],
    surfaces: ["minha-conta", "dashboard"],
    modules: ["src/app/lib/auth.ts", "src/app/api/conta"],
  },
  Payment: {
    id: "Payment",
    label: "Pagamento",
    dependsOn: ["User"],
    affects: ["Appointment", "Service", "Coupon", "Plan", "Dashboard", "Statistics"],
    usedBy: ["processPaymentWebhook", "workflow", "asaas"],
    producesEvents: ["PaymentConfirmed", "PaymentRefunded", "PaymentCancelled"],
    consumesEvents: [],
    surfaces: ["pagamentos", "minha-conta", "dashboard", "estatisticas"],
    modules: ["src/app/lib/process-payment-webhook.ts", "src/app/lib/domain/workflow.ts"],
  },
  Appointment: {
    id: "Appointment",
    label: "Agendamento",
    dependsOn: ["User", "Payment", "Coupon"],
    affects: ["Service", "Coupon", "Dashboard", "Statistics", "Synchronization"],
    usedBy: ["workflow", "agendamento", "admin"],
    producesEvents: [
      "AppointmentReserved",
      "AppointmentAccepted",
      "AppointmentRejected",
      "AppointmentCancelled",
      "AppointmentRebooked",
      "AppointmentStarted",
    ],
    consumesEvents: ["PaymentConfirmed"],
    surfaces: ["agenda", "admin-agendamentos", "minha-conta", "dashboard"],
    modules: ["src/app/lib/domain/workflow.ts", "src/app/api/agendamentos"],
  },
  Service: {
    id: "Service",
    label: "Serviço",
    dependsOn: ["User", "Appointment"],
    affects: ["Dashboard", "Statistics", "Synchronization"],
    usedBy: ["workflow", "admin-servicos"],
    producesEvents: ["ServiceStarted", "ServiceCompleted", "ServiceCancelled"],
    consumesEvents: ["AppointmentAccepted", "AppointmentStarted"],
    surfaces: ["servicos-gerais", "servicos-selecionados", "minha-conta", "dashboard"],
    modules: ["src/app/lib/domain/workflow.ts", "src/app/api/admin/servicos"],
  },
  Coupon: {
    id: "Coupon",
    label: "Cupom",
    dependsOn: ["User", "Payment", "Plan"],
    affects: ["Appointment", "Payment", "Dashboard"],
    usedBy: ["validate-coupon-checkout", "agendamentos/com-cupom"],
    producesEvents: ["CouponGenerated", "CouponConsumed", "CouponExpired"],
    consumesEvents: ["PaymentConfirmed", "PlanActivated", "AppointmentCancelled"],
    surfaces: ["cupons", "minha-conta", "agendamento"],
    modules: ["src/app/lib/validate-coupon-checkout.ts", "src/app/lib/coupons.ts"],
  },
  Plan: {
    id: "Plan",
    label: "Plano",
    dependsOn: ["User", "Payment"],
    affects: ["Coupon", "Dashboard", "Statistics"],
    usedBy: ["planos", "workflow"],
    producesEvents: ["PlanActivated", "PlanCancelled", "PlanRenewed", "PlanExpired"],
    consumesEvents: ["PaymentConfirmed"],
    surfaces: ["planos", "minha-conta", "dashboard", "estatisticas"],
    modules: ["src/app/lib/asaas-plano-payment-effects.ts", "src/app/api/planos"],
  },
  Statistics: {
    id: "Statistics",
    label: "Estatísticas",
    dependsOn: ["User", "Payment", "Appointment", "Service", "Plan"],
    affects: [],
    usedBy: ["admin/estatisticas"],
    producesEvents: [],
    consumesEvents: [
      "PaymentConfirmed",
      "AppointmentReserved",
      "ServiceCompleted",
      "PlanActivated",
      "PlanCancelled",
    ],
    surfaces: ["estatisticas", "dashboard"],
    modules: ["src/app/api/admin/stats"],
  },
  Dashboard: {
    id: "Dashboard",
    label: "Dashboard Admin",
    dependsOn: ["Payment", "Appointment", "Service", "Coupon", "Plan", "Statistics"],
    affects: [],
    usedBy: ["admin"],
    producesEvents: [],
    consumesEvents: ["PaymentConfirmed", "AppointmentReserved", "ServiceCompleted", "PlanCancelled"],
    surfaces: ["dashboard"],
    modules: ["src/app/admin/page.tsx", "src/app/api/admin/stats"],
  },
  Admin: {
    id: "Admin",
    label: "Admin",
    dependsOn: ["User", "Workflow"],
    affects: ["Appointment", "Service", "Payment", "Coupon", "Plan"],
    usedBy: ["admin routes"],
    producesEvents: [],
    consumesEvents: ["AppointmentCancelled", "PaymentRefunded"],
    surfaces: ["admin-agendamentos", "admin-servicos", "pagamentos", "planos"],
    modules: ["src/app/api/admin"],
  },
  Notification: {
    id: "Notification",
    label: "Notificação",
    dependsOn: ["User"],
    affects: [],
    usedBy: ["sendEmail", "webhooks"],
    producesEvents: [],
    consumesEvents: ["PaymentConfirmed", "PlanActivated", "ServiceCompleted"],
    surfaces: [],
    modules: ["src/app/lib/sendEmail.ts"],
  },
  Synchronization: {
    id: "Synchronization",
    label: "Synchronization Engine",
    dependsOn: ["Workflow"],
    affects: ["Dashboard", "Statistics", "Admin", "User"],
    usedBy: ["DomainSyncProvider", "hooks"],
    producesEvents: ["SyncEnvelope"],
    consumesEvents: [
      "PaymentConfirmed",
      "AppointmentReserved",
      "AppointmentCancelled",
      "AppointmentRebooked",
      "ServiceCompleted",
      "PlanCancelled",
      "PaymentRefunded",
    ],
    surfaces: [
      "minha-conta",
      "dashboard",
      "agenda",
      "pagamentos",
      "cupons",
      "planos",
      "estatisticas",
      "admin-agendamentos",
      "servicos-gerais",
      "servicos-selecionados",
    ],
    modules: ["src/app/lib/synchronization"],
  },
  Workflow: {
    id: "Workflow",
    label: "Workflow / State Machine",
    dependsOn: [],
    affects: ["Payment", "Appointment", "Service", "Coupon", "Synchronization"],
    usedBy: ["execution-core", "admin", "test-engine", "simulation"],
    producesEvents: ["DomainEvent", "TransitionRecorded"],
    consumesEvents: [],
    surfaces: [],
    modules: ["src/app/lib/domain/workflow.ts", "src/app/lib/domain/state-machine"],
  },
};

export function listGraphEntityIds(): GraphEntityId[] {
  return Object.keys(DOMAIN_GRAPH_NODES) as GraphEntityId[];
}

export function getGraphNode(id: GraphEntityId): GraphNode {
  return DOMAIN_GRAPH_NODES[id];
}
