ALTER TABLE "UserPlan" ADD COLUMN IF NOT EXISTS "refundRequestedAt" TIMESTAMP(3);
ALTER TABLE "UserPlan" ADD COLUMN IF NOT EXISTS "refundAmount" DOUBLE PRECISION;
ALTER TABLE "UserPlan" ADD COLUMN IF NOT EXISTS "refundAsaasStatus" TEXT;
ALTER TABLE "UserPlan" ADD COLUMN IF NOT EXISTS "refundUserConfirmedAt" TIMESTAMP(3);
ALTER TABLE "UserPlan" ADD COLUMN IF NOT EXISTS "refundUserDisputedAt" TIMESTAMP(3);
